### ISSUE TITLE
CPU compatibility 

### ISSUE THREAD

**Issue by haniraid** [jagennath-hari/DepthStream-Accelerator-ROS2-Integrated-Monocular-Depth-Inference#1]
Hi. so i need to run this project without GPU. i just want to know whether its possible or not

**Comment by jagennath-hari** [comment]
Hello, 

Yes, it is possible to run in the CPU. Take a look at depth.py in the scripts folder, I made some initial code in python to deploy ZoeDepth in ROS. You should be able to make very minimal changes, and it should work on the CPU. 

If you want low latency loops, you would need to use the ONNX model directly. You should look into the ONNX, ONNX runtime etc to deploy the network in C++ on the CPU.

Regards
